### ISSUE TITLE
Version 9.5.1 is sending `react-9.5.1-beta.1` in `ixlib` param

### ISSUE THREAD

**Issue by jayeb** [imgix/react-imgix#870] opened 2022-06-09 21:25 UTC
**Before you submit:**

- [x] Please search through the existing issues (both open AND closed) to see if your issue has been discussed before. GitHub issue search can be used for this: https://github.com/imgix/react-imgix/issues?utf8=%E2%9C%93&q=is%3Aissue
- [x] Please ensure the problem has been isolated and reduced. This link explains more: http://css-tricks.com/6263-reduced-test-cases/

**Describe the bug**

Hey folks! I just noticed that despite having my installed version pinned to `9.5.1`, I'm seeing `ixlib=react-9.5.1-beta.1` included in generated URLs.

**To Reproduce**

Steps to reproduce the behaviour:

1. Install version 9.5.1
2. Use the `<Imgix>` component *without* setting `disableLibraryParam={true}`.
3. Examine the resultant `src` and `srcset` values

I've added a CodeSandbox here that demonstrates: https://codesandbox.io/s/boring-firefly-iifjo3?file=/src/index.js

**Expected behaviour**
The `ixlib` parameter should be set to `react-9.5.1`, without the `-beta.1` suffix.

**Information:**

- react-imgix version: 9.5.1
- browser version: Probably not relevant, but I'm flattered that you asked! I'm on [Chrome 102](https://www.whatsmybrowser.org/b/K28XU).

**Additional context**
👋 Hello! Just got imgix integrated into our app and as expected it's been great so far. Miss you all!

**Comment by sherwinski** [comment] 2022-06-09 22:57
Hey @jayeb! Thanks for calling this out. One of us (most likely me) will look into this sometime over the next week.
Hope you're doing well 🥳

**Comment by sherwinski** [comment] 2022-06-22 20:16
Hey @jayeb, our team did some digging and we _think_ this is a one-off issue caused by #868 . Unfortunately, there isn't any real code change we can make to remediate it at this point but we suspect things will be fixed once the latest stable release is published.

**Closed** 2022-07-26 19:26 UTC

**Comment by sherwinski** [comment] 2022-07-26 19:40
Confirmed this is fixed in the latest release, thanks again @jayeb!

**Comment by jayeb** [comment] 2022-07-26 19:50
Thats a doozy! Thanks for fixing, Sherwin.
