### ISSUE TITLE
With aggressiveLoad true, on Safari, it's loading full size images

### ISSUE THREAD

**Issue by kamui** [imgix/react-imgix#45] opened 2016-09-10 20:06 UTC
We've been seeing an issue on Safari, where if we turn on `aggressiveLoad={true}`, every image gets loaded on Safari (mobile and desktop 9.x) with `w=1&h=1` and this fetches the original images sizes. This is bloating the payload and on some phones crashing Safari.

If I inspect source in the Safari inspector, I don't see `w=1&h=1`, I see the correct width `w=400&h=1`. This is made worse if you leave `generateSrcSet` on since it'll fetch all srcs at the original size for some reason.

We've only seen this on Safari, it works fine everywhere else.

**Comment by kamui** [comment] 2016-09-10 20:10
We use https://github.com/kadirahq/react-storybook and I've tested this specific bug with an isolated component render and I see 2 requests, one for the original full size, and one for the smaller size.

**Comment by frederickfogerty** [comment] 2016-09-11 20:27
I must not understand, because this is how `aggressiveLoad` is intended to work. Are you setting the dimensions manually, or are you expecting it to work out the dimensions itself? If you are expecting the latter, and don't want the aggressive loading of the image, turn off `aggressiveLoad`.

Hope this helps!

**Comment by kamui** [comment] 2016-09-11 20:28
Maybe I don't understand how `aggressiveLoad` is supposed to work, but at the very least, is it supposed to behave the same way on Safari and all other browsers? Because at the very least, we're seeing Safari work completely differently. I'm seeing Safari always make 2 requests for the image, where all other browsers make 1.

**Comment by Grsmto** [comment] 2017-01-15 21:20
I'm having the same issue even without the `aggressiveLoad` prop.

**Comment by superfunkminister** [comment] 2017-01-15 21:27
+1

**Comment by frederickfogerty** [comment] 2017-02-06 19:57
Hey @modosc, are you able to update the `picture` behaviour to fix the bug that @Grsmto has uncovered by any chance?

**Comment by modosc** [comment] 2017-02-06 20:33
yeah - let me take a look.

**Comment by modosc** [comment] 2017-02-06 23:46
@frederickfogerty maybe i'm misunderstanding, but isn't that the expected default behavior if you don't explicitly provide a width/height to `<Imgix type='img'>`?

**Comment by Grsmto** [comment] 2017-02-06 23:55
Yeah the behaviour I detailed seems to be fine. So it may not be related to the original issue.

**Comment by frederickfogerty** [comment] 2017-02-07 00:01
Cheers @modosc - it's meant to render at the size of the image in the DOM by default, but it sounds like if this is server rendering, then there is no size of the image, and so it's back to the original issue. Thanks!

**Comment by modosc** [comment] 2017-02-07 00:04
>  but it sounds like if this is server rendering, then there is no size of the image, and so it's back to the original issue. Thanks!

yeah, that's what i'm seeing here too. maybe we should emit some sort of warning if that's happening (ie, if we assemble any url with `h=1&w=1`? anyway i'm unassigning this for now. i spent a few minutes trying to figure out what was happening in safari without any luck.

**Comment by modosc** [comment] 2017-03-21 20:23
> Edit: issue seems to be coming from the generated fallback <img> element with the Picture Support. You need to define the width/height of the image on the parent <Imgix/> element otherwise it will load the 1x1 version by default on the fallback <img>! (crashing Safari/mobiles if you have big images by default).

something else i noticed yesterday in my work's codebase - you not only have to have a width/height on the parent element but it also needs to be the maximum width/height of any of the `<source>` elements that may be inside of the generated `<picture>`. so this:
```
<Imgix type="picture" src={src} width={100} height={100}>
  <Imgix type="source" src={src} width={400} height={100} imgProps={{ media: '(min-width: 768px)' }} />
</Imgix>
```

will load the 400x100 image on a large screen but will only display it as 100x100 (at least in chrome and safari)

i _think_ this is a bug - in my local testing setting the provided height/width on the fallback image but changing the same attributes on the parent container to the maximum values did the right thing everywhere. working around it doesn't seem hard but it's unclear if that's the expected behavior though. should i just open a new bug to discuss this?

**Comment by frederickfogerty** [comment] 2017-03-21 21:30
Yeah that sounds like a bug @modosc.

Exposing a prop like `fallbackImageDimensions` could be a good idea here to set the fallback dimensions, and have the `width` and `height` set the `picture` element's props (as it does now).

**Comment by danielfarrell** [comment] 2017-12-12 21:58
I found that I could get a working solution for us by using `defaultHeight` and `defaultWidth` props along with `aggressiveLoad`.  We use it with Gatsby for static site generation, and Safari was causing issues by not getting updated.  This solution of setting mobile height/width is "good enough" for our use case though.  Those props are not documented, but are used here: https://github.com/imgix/react-imgix/blob/master/src/index.js#L16-L31

**Comment by frederickfogerty** [comment] 2018-07-01 20:22
I'm going to close this as there doesn't seem to be a reduced test case I can work with. Please comment here or open a new issue if anyone has issues in the future.

**Closed by frederickfogerty** 2018-07-01 20:22 UTC
Labels: Priority: Medium, Status: Discussion, Type: Bug
